// src/lib/winter94Program.ts

export type DayProgram = {
  throwingTime: string;
  throwingDistance: string;
  flatGround: string;
  bullpen: string;
};

export const PROGRAM_START = "2025-12-01";
export const PROGRAM_END = "2026-02-28";

export const programMap: Record<string, DayProgram> = {
  "2025-12-01": {
    throwingTime: "10 minutes",
    throwingDistance: "75 ft",
    flatGround: "15 Pitches (all fastballs)",
    bullpen: "",
  },
  "2025-12-02": {
    throwingTime: "10 minutes",
    throwingDistance: "75 ft",
    flatGround: "15 Pitches (all fastballs)",
    bullpen: "",
  },
  "2025-12-03": {
    throwingTime: "",
    throwingDistance: "",
    flatGround: "",
    bullpen: "",
  },
  "2025-12-04": {
    throwingTime: "10 minutes",
    throwingDistance: "75 ft",
    flatGround: "15 Pitches (all fastballs)",
    bullpen: "",
  },
  "2025-12-05": {
    throwingTime: "10 minutes",
    throwingDistance: "75 ft",
    flatGround: "15 Pitches (all fastballs)",
    bullpen: "",
  },
  "2025-12-06": {
    throwingTime: "10 minutes",
    throwingDistance: "90 ft",
    flatGround: "15 Pitches (all fastballs)",
    bullpen: "",
  },
  "2025-12-07": {
    throwingTime: "",
    throwingDistance: "",
    flatGround: "",
    bullpen: "",
  },
  "2025-12-08": {
    throwingTime: "10 minutes",
    throwingDistance: "90 ft",
    flatGround: "15 Pitches (all fastballs)",
    bullpen: "",
  },
  "2025-12-09": {
    throwingTime: "10 minutes",
    throwingDistance: "90 ft",
    flatGround: "15 Pitches (all fastballs)",
    bullpen: "",
  },
  "2025-12-10": {
    throwingTime: "",
    throwingDistance: "",
    flatGround: "",
    bullpen: "",
  },
  "2025-12-11": {
    throwingTime: "10 minutes",
    throwingDistance: "105 ft",
    flatGround: "15 Pitches (all fastballs)",
    bullpen: "",
  },
  "2025-12-12": {
    throwingTime: "10 minutes",
    throwingDistance: "105 ft",
    flatGround: "15 Pitches (all fastballs)",
    bullpen: "",
  },
  "2025-12-13": {
    throwingTime: "10 minutes",
    throwingDistance: "120 ft",
    flatGround: "15 Pitches (all fastballs)",
    bullpen: "",
  },
  "2025-12-14": {
    throwingTime: "",
    throwingDistance: "",
    flatGround: "",
    bullpen: "",
  },
  "2025-12-15": {
    throwingTime: "10 minutes",
    throwingDistance: "120 ft",
    flatGround: "15 Pitches (all fastballs)",
    bullpen: "",
  },
  "2025-12-16": {
    throwingTime: "10 minutes",
    throwingDistance: "120 ft",
    flatGround: "15 Pitches (all fastballs)",
    bullpen: "",
  },
  "2025-12-17": {
    throwingTime: "",
    throwingDistance: "",
    flatGround: "",
    bullpen: "",
  },
  "2025-12-18": {
    throwingTime: "10 minutes",
    throwingDistance: "135 ft",
    flatGround: "15 Pitches (all fastballs)",
    bullpen: "",
  },
  "2025-12-19": {
    throwingTime: "10 minutes",
    throwingDistance: "135 ft",
    flatGround: "15 Pitches (all fastballs)",
    bullpen: "",
  },
  "2025-12-20": {
    throwingTime: "10 minutes",
    throwingDistance: "150 ft",
    flatGround: "15 Pitches (all fastballs)",
    bullpen: "",
  },
  "2025-12-21": {
    throwingTime: "",
    throwingDistance: "",
    flatGround: "",
    bullpen: "",
  },
  "2025-12-22": {
    throwingTime: "10 minutes",
    throwingDistance: "150 ft",
    flatGround: "15 Pitches (all fastballs)",
    bullpen: "",
  },
  "2025-12-23": {
    throwingTime: "10 minutes",
    throwingDistance: "150 ft",
    flatGround: "15 Pitches (all fastballs)",
    bullpen: "",
  },
  "2025-12-24": {
    throwingTime: "",
    throwingDistance: "",
    flatGround: "",
    bullpen: "",
  },
  "2025-12-25": {
    throwingTime: "10 minutes",
    throwingDistance: "165 ft",
    flatGround: "15 Pitches (all fastballs)",
    bullpen: "",
  },
  "2025-12-26": {
    throwingTime: "10 minutes",
    throwingDistance: "165 ft",
    flatGround: "15 Pitches (all fastballs)",
    bullpen: "",
  },
  "2025-12-27": {
    throwingTime: "10 minutes",
    throwingDistance: "180 ft",
    flatGround: "15 Pitches (all fastballs)",
    bullpen: "",
  },
  "2025-12-28": {
    throwingTime: "",
    throwingDistance: "",
    flatGround: "",
    bullpen: "",
  },
  "2025-12-29": {
    throwingTime: "10 minutes",
    throwingDistance: "180 ft",
    flatGround: "15 Pitches (all fastballs)",
    bullpen: "",
  },
  "2025-12-30": {
    throwingTime: "10 minutes",
    throwingDistance: "180 ft",
    flatGround: "15 Pitches (all fastballs)",
    bullpen: "",
  },
  "2025-12-31": {
    throwingTime: "",
    throwingDistance: "",
    flatGround: "",
    bullpen: "",
  },
  "2026-01-01": {
    throwingTime: "",
    throwingDistance: "",
    flatGround: "",
    bullpen: "",
  },
  "2026-01-02": {
    throwingTime: "15 minutes",
    throwingDistance: "180 ft",
    flatGround: "15 Pitches (all fastballs)",
    bullpen: "",
  },
  "2026-01-03": {
    throwingTime: "15 minutes",
    throwingDistance: "195 ft",
    flatGround: "15 Pitches (all fastballs)",
    bullpen: "",
  },
  "2026-01-04": {
    throwingTime: "",
    throwingDistance: "",
    flatGround: "",
    bullpen: "",
  },
  "2026-01-05": {
    throwingTime: "15 minutes",
    throwingDistance: "195 ft",
    flatGround: "15 Pitches (all fastballs)",
    bullpen: "",
  },
  "2026-01-06": {
    throwingTime: "15 minutes",
    throwingDistance: "195 ft",
    flatGround: "15 Pitches (all fastballs)",
    bullpen: "",
  },
  "2026-01-07": {
    throwingTime: "",
    throwingDistance: "",
    flatGround: "",
    bullpen: "",
  },
  "2026-01-08": {
    throwingTime: "15 minutes",
    throwingDistance: "210 ft",
    flatGround: "15 Pitches (all fastballs)",
    bullpen: "",
  },
  "2026-01-09": {
    throwingTime: "15 minutes",
    throwingDistance: "210 ft",
    flatGround: "15 Pitches (all fastballs)",
    bullpen: "",
  },
  "2026-01-10": {
    throwingTime: "15 minutes",
    throwingDistance: "225 ft",
    flatGround: "15 Pitches (all fastballs)",
    bullpen: "",
  },
  "2026-01-11": {
    throwingTime: "",
    throwingDistance: "",
    flatGround: "",
    bullpen: "",
  },
  "2026-01-12": {
    throwingTime: "15 minutes",
    throwingDistance: "225 ft",
    flatGround: "15 Pitches (all fastballs)",
    bullpen: "",
  },
  "2026-01-13": {
    throwingTime: "15 minutes",
    throwingDistance: "225 ft",
    flatGround: "15 Pitches (all fastballs)",
    bullpen: "",
  },
  "2026-01-14": {
    throwingTime: "",
    throwingDistance: "",
    flatGround: "",
    bullpen: "",
  },
  "2026-01-15": {
    throwingTime: "15 minutes",
    throwingDistance: "240 ft",
    flatGround: "15 Pitches (all fastballs)",
    bullpen: "",
  },
  "2026-01-16": {
    throwingTime: "15 minutes",
    throwingDistance: "240 ft",
    flatGround: "15 Pitches (all fastballs)",
    bullpen: "",
  },
  "2026-01-17": {
    throwingTime: "15 minutes",
    throwingDistance: "255 ft",
    flatGround: "15 Pitches (all fastballs)",
    bullpen: "",
  },
  "2026-01-18": {
    throwingTime: "",
    throwingDistance: "",
    flatGround: "",
    bullpen: "",
  },
  "2026-01-19": {
    throwingTime: "25 minutes +",
    throwingDistance: "300+ ft",
    flatGround: "",
    bullpen:
      "60 Pitches (25 FB, 15 CH, 15 CU; 1-2 Hitters)",
  },
  "2026-01-20": {
    throwingTime: "15 minutes",
    throwingDistance: "255 ft",
    flatGround: "15 Pitches (all fastballs)",
    bullpen: "",
  },
  "2026-01-21": {
    throwingTime: "",
    throwingDistance: "",
    flatGround: "",
    bullpen: "",
  },
  "2026-01-22": {
    throwingTime: "15 minutes",
    throwingDistance: "270 ft",
    flatGround: "",
    bullpen: "20 pitch light pen (all fastballs)",
  },
  "2026-01-23": {
    throwingTime: "15 minutes",
    throwingDistance: "270 ft",
    flatGround: "15 Pitches (all fastballs)",
    bullpen: "",
  },
  "2026-01-24": {
    throwingTime: "15 minutes",
    throwingDistance: "285 ft",
    flatGround: "15 Pitches (all fastballs)",
    bullpen: "",
  },
  "2026-01-25": {
    throwingTime: "",
    throwingDistance: "",
    flatGround: "",
    bullpen: "",
  },
  "2026-01-26": {
    throwingTime: "15 minutes",
    throwingDistance: "285 ft",
    flatGround: "15 Pitches (all fastballs)",
    bullpen: "",
  },
  "2026-01-27": {
    throwingTime: "15 minutes",
    throwingDistance: "285 ft",
    flatGround: "15 Pitches (all fastballs)",
    bullpen: "",
  },
  "2026-01-28": {
    throwingTime: "",
    throwingDistance: "",
    flatGround: "",
    bullpen: "",
  },
  "2026-01-29": {
    throwingTime: "15 minutes",
    throwingDistance: "300 ft",
    flatGround: "",
    bullpen: "25 pitch pen (all fastballs)",
  },
  "2026-01-30": {
    throwingTime: "15 minutes",
    throwingDistance: "300 ft",
    flatGround: "15 Pitches (all fastballs)",
    bullpen: "",
  },
  "2026-01-31": {
    throwingTime: "15 minutes",
    throwingDistance: "300 ft",
    flatGround: "15 Pitches (all fastballs)",
    bullpen: "",
  },
  "2026-02-01": {
    throwingTime: "",
    throwingDistance: "",
    flatGround: "",
    bullpen: "",
  },
  "2026-02-02": {
    throwingTime: "15 minutes",
    throwingDistance: "300 ft",
    flatGround: "15 Pitches (all fastballs)",
    bullpen: "",
  },
  "2026-02-03": {
    throwingTime: "15 minutes",
    throwingDistance: "300 ft",
    flatGround: "15 Pitches (all fastballs)",
    bullpen: "",
  },
  "2026-02-04": {
    throwingTime: "",
    throwingDistance: "",
    flatGround: "",
    bullpen: "",
  },
  "2026-02-05": {
    throwingTime: "15 minutes",
    throwingDistance: "300 ft",
    flatGround: "",
    bullpen: "35 pitch pen (all fastballs)",
  },
  "2026-02-06": {
    throwingTime: "15 minutes",
    throwingDistance: "300 ft",
    flatGround: "15 Pitches (all fastballs)",
    bullpen: "",
  },
  "2026-02-07": {
    throwingTime: "15 minutes",
    throwingDistance: "300 ft",
    flatGround: "15 Pitches (all fastballs)",
    bullpen: "",
  },
  "2026-02-08": {
    throwingTime: "",
    throwingDistance: "",
    flatGround: "",
    bullpen: "",
  },
  "2026-02-09": {
    throwingTime: "15 minutes",
    throwingDistance: "300 ft",
    flatGround: "20 Pitches (15 FB, 5 CH)",
    bullpen: "",
  },
  "2026-02-10": {
    throwingTime: "15 minutes",
    throwingDistance: "300 ft",
    flatGround: "20 Pitches (15 FB, 5 CH)",
    bullpen: "",
  },
  "2026-02-11": {
    throwingTime: "",
    throwingDistance: "",
    flatGround: "",
    bullpen: "",
  },
  "2026-02-12": {
    throwingTime: "20 minutes",
    throwingDistance: "300 ft",
    flatGround: "",
    bullpen: "45 pitch pen (FB/CH/CU mix)",
  },
  "2026-02-13": {
    throwingTime: "15 minutes",
    throwingDistance: "300 ft",
    flatGround: "20 Pitches (15 FB, 5 CH)",
    bullpen: "",
  },
  "2026-02-14": {
    throwingTime: "15 minutes",
    throwingDistance: "300 ft",
    flatGround: "20 Pitches (15 FB, 5 CH)",
    bullpen: "",
  },
  "2026-02-15": {
    throwingTime: "",
    throwingDistance: "",
    flatGround: "",
    bullpen: "",
  },
  "2026-02-16": {
    throwingTime: "15 minutes",
    throwingDistance: "300 ft",
    flatGround: "20 Pitches (15 FB, 5 CH)",
    bullpen: "",
  },
  "2026-02-17": {
    throwingTime: "15 minutes",
    throwingDistance: "300 ft",
    flatGround: "20 Pitches (15 FB, 5 CH)",
    bullpen: "",
  },
  "2026-02-18": {
    throwingTime: "",
    throwingDistance: "",
    flatGround: "",
    bullpen: "",
  },
  "2026-02-19": {
    throwingTime: "20 minutes",
    throwingDistance: "300 ft",
    flatGround: "",
    bullpen: "50 pitch pen (FB/CH/CU mix; 2 hitters)",
  },
  "2026-02-20": {
    throwingTime: "15 minutes",
    throwingDistance: "300 ft",
    flatGround: "20 Pitches (15 FB, 5 CH)",
    bullpen: "",
  },
  "2026-02-21": {
    throwingTime: "15 minutes",
    throwingDistance: "300 ft",
    flatGround: "20 Pitches (15 FB, 5 CH)",
    bullpen: "",
  },
  "2026-02-22": {
    throwingTime: "",
    throwingDistance: "",
    flatGround: "",
    bullpen: "",
  },
  "2026-02-23": {
    throwingTime: "15 minutes",
    throwingDistance: "300 ft",
    flatGround: "20 Pitches (15 FB, 5 CH)",
    bullpen: "",
  },
  "2026-02-24": {
    throwingTime: "15 minutes",
    throwingDistance: "300 ft",
    flatGround: "20 Pitches (15 FB, 5 CH)",
    bullpen: "",
  },
  "2026-02-25": {
    throwingTime: "",
    throwingDistance: "",
    flatGround: "",
    bullpen: "",
  },
  "2026-02-26": {
    throwingTime: "20 minutes",
    throwingDistance: "300 ft",
    flatGround: "",
    bullpen: "60 pitch pen (FB/CH/CU mix; 2-3 hitters)",
  },
  "2026-02-27": {
    throwingTime: "10 minutes",
    throwingDistance: "240 ft",
    flatGround: "20 Pitches (15 FB, 5 CH)",
    bullpen: "",
  },
    "2026-02-28": {
    throwingTime: "",
    throwingDistance: "",
    flatGround: "",
    bullpen: "",
  },
};
